### ISSUE TITLE
设置target之后tag不管用，会弹出多个toast，第一个remove时就会闪退

### ISSUE THREAD

**Issue by xvalerian** [bravinshi/BToast#2]
报错信息
java.lang.IllegalArgumentException: View=com.bravin.btoast.view.AnimationLayout{7e083a5 V.E...... .......D 0,0-970,76 #7f08001b app:id/al_layout} not attached to window manager
        at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:529)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:438)
        at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:121)
        at com.bravin.btoast.BToast$MainThreadHandler.handleMessage(BToast.java:180)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6812)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by bravinshi** [comment]
我按照你所说的使用方式测试一遍，没有出现你这说的情况，能把你的代码片段也贴上来吗

**Comment by bravinshi** [comment]
问题已经修复，这是因为activity在finished后view已经被销毁，所以再去移除这个view会报这个错误
类似可参考:https://stackoverflow.com/questions/22924825/view-not-attached-to-window-manager-crash
